### ISSUE TITLE
Found 0 power devices - Jetson Xavier NX

### ISSUE THREAD

**Issue by mingyusoton** [opendr-eu/jetson_power#1]
```
[OpenDR PowerLogger] Found 0 power devices
[OpenDR PowerLogger] Estimating background power load for 3 s, please do not use the system.
[OpenDR PowerLogger] Idle power:   0.000 mW
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'Measurement' object is not callable
```

Hi, I meet with this error with my Jetson Xavier NX (Jetpack 5.1.1). Do you have any suggestions? Thank you!

**Comment by passalis** [comment]
Hi, you can check where i2c is exposed in your system and then appropriately edit the following line:

https://github.com/opendr-eu/jetson_power/blob/main/p_est.py#L21

You are looking for `iio:device0`. Typically, these can be found in paths like  `/sys/bus/i2c/drivers/ina3221x/` or 
 `/sys/devices/3160000.i2c/i2c-0/`.

You might also have to run the program as root. Please check https://forums.developer.nvidia.com/t/iio-device-symlink-missing/209612

**Comment by mingyusoton** [comment]
> Hi, you can check where i2c is exposed in your system and then appropriately edit the following line:
> 
> https://github.com/opendr-eu/jetson_power/blob/main/p_est.py#L21
> 
> You are looking for `iio:device0`. Typically, these can be found in paths like `/sys/bus/i2c/drivers/ina3221x/` or `/sys/devices/3160000.i2c/i2c-0/`.
> 
> You might also have to run the program as root. Please check https://forums.developer.nvidia.com/t/iio-device-symlink-missing/209612

Thank you!

**Comment by hafizuriu** [comment]
I'm facing the same error on my jetson orin nano

```
[OpenDR PowerLogger] Found 0 power devices
[OpenDR PowerLogger] Estimating background power load for 3 s, please do not use the system.
[OpenDR PowerLogger] Idle power:   0.000 mW```

How can I solve this?
